# Form implementation generated from reading ui file 'WRecomendaciones.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormRecomendaciones(object):
    def setupUi(self, FormRecomendaciones):
        FormRecomendaciones.setObjectName("FormRecomendaciones")
        FormRecomendaciones.resize(1160, 755)
        self.label_2 = QtWidgets.QLabel(parent=FormRecomendaciones)
        self.label_2.setGeometry(QtCore.QRect(460, 20, 251, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=FormRecomendaciones)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Iconos/inicio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=FormRecomendaciones)
        self.label.setGeometry(QtCore.QRect(0, 0, 1161, 755))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Imagenes/UsuarioLogeado.png"))
        self.label.setObjectName("label")
        self.widgetRecomendaciones = QtWidgets.QWidget(parent=FormRecomendaciones)
        self.widgetRecomendaciones.setGeometry(QtCore.QRect(220, 140, 731, 401))
        self.widgetRecomendaciones.setObjectName("widgetRecomendaciones")
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.widgetRecomendaciones.raise_()

        self.retranslateUi(FormRecomendaciones)
        QtCore.QMetaObject.connectSlotsByName(FormRecomendaciones)

    def retranslateUi(self, FormRecomendaciones):
        _translate = QtCore.QCoreApplication.translate
        FormRecomendaciones.setWindowTitle(_translate("FormRecomendaciones", "::Recomendaciones"))
        self.label_2.setText(_translate("FormRecomendaciones", "Recomedaciones"))
        self.pushButton.setText(_translate("FormRecomendaciones", "Inicio"))
