from enum import Enum

class TipoTransaccion(Enum):
    ALIMENTACION = "ALIMENTACION"
    TRASPORTE = "TRASPORTE"
    SALUD = "SALUD"
    VESTIMENTA = "VESTIMENTA"
    EDUCACION = "EDUCACION"
    CUIDADO_PERSONAL = "CUIDADO PERSONAL"
    SUSCRIPCION = "SUBSCRIPCION"
    RENTA = "RENTA"
    SERVICIOS_BASICOS = "SERVICIOS BASICOS"
    MANTENIMIENTO_HOGAR = "MANTENIMIENTO HOGAR"
    OTROS = "OTROS"
